### ISSUE TITLE
std::default::Default not implemented for no-deadlocks::Mutes

### ISSUE THREAD

**Issue by cameronelliott** [p-avital/no-deadlocks#10]
hey, this package is pretty awesome!
I tried both this and parking_lot, but I love how you keep the original lock stack frame also. (for re-entrancy issues)

I discovered in moving some code from std::sync::Mutex to this, that std::default::Default is not
implemented on the Mutex here.

Let me know if you'd like a PR, I'm pretty new to Rust, but think I might be able to hack this.

**Comment by p-avital** [comment]
Hi,

Glad you like it!

I do tend to miss bits of the APIs I attempt to copy in my crates, I'd love a PR, `Default` is not hard to implement but [`zenoh`](https://github.com/eclipse-zenoh/zenoh) now takes 100% of my time.

Thanks for spotting it :)

**Comment by p-avital** [comment]
Took a while, but here it is :)
