### ISSUE TITLE
graph doesn't work with HashMap implementation (default-features = false)

### ISSUE THREAD

**Issue by BigBadE** [p-avital/no-deadlocks#11]
In graphs, NodeType doesn't implement Eq or Hash, so it can't be a key of the hashmap. Trying to compile no_deadlocks with the use_vecmap feature disabled doesn't compile.

It should be an easy fix by adding the bounds of Eq and Hash to Graph and making DependencyNode derive Hash, if the owner of this repository is still active and doesn't want to fix it I can make a PR for it tomorrow. The vecmap implementation severely slows down larger programs with lots of locks.

**Comment by p-avital** [comment]
Hi there,
I haven't worked on this create for a while because of other priorities and it's apparent lack of use, but PRs are very welcome :)

**Comment by BigBadE** [comment]
Will this be in a release sometime soon?

**Comment by p-avital** [comment]
I'll try to remember to make one tomorrow :)

**Comment by BigBadE** [comment]
Ok, thank you!

**Comment by p-avital** [comment]
Just published, thanks for your work :)
