### ISSUE TITLE
RwLock is missing into_inner

### ISSUE THREAD

**Issue by uberFoo** [p-avital/no-deadlocks#13]
I switched to no-deadlocks because I'm having some race condition and when swapping over I found into_inner is missing from RwLock. I see that it's commented out in the code, which of course does not work.

**Comment by p-avital** [comment]
Hi @uberFoo,
Thanks for letting me know, I've just pushed and published v`1.3.2` which now has a valid implementation of `into_inner` :)

**Comment by uberFoo** [comment]
Wow — thanks! - KeithOn Nov 19, 2023, at 04:54, Pierre Avital ***@***.***> wrote:﻿
Hi @uberFoo,
Thanks for letting me know, I've just pushed and published v1.3.2 which now has a valid implementation of into_inner :)
