### ISSUE TITLE
impl Sync for T: Send

### ISSUE THREAD

**Issue by GTRI-nathan** [p-avital/no-deadlocks#2]
Cool crate!
When using it, I had to modify Mutex to add a line like https://doc.rust-lang.org/src/std/sync/mutex.rs.html#182 from the std Mutex implementation, as I was using a data type that was Send but not Sync.
I opened this issue as it seems like the API difference from std might be a bug.
Best,
Nathan

**Comment by p-avital** [comment]
Thanks for the report, fixed it for both `Mutex` and `RwLock`. Published on [crates.io](crates.io) as version `1.1.0` :)
Hope this crate helps :)
