### ISSUE TITLE
Analyze after Timeout

### ISSUE THREAD

**Issue by michaelsippel** [p-avital/no-deadlocks#6]
If I understand it correctly, everytime a lock could not be taken the analyze() function is called. This is probably responsible for the huge slowdown. Maybe it is possible to analyze the graph only after for a certain (configurable) time the lock could not be taken?
Currently I'm not successful in reproducing my deadlock.

**Comment by p-avital** [comment]
PR merged to `dev` branch, going to try to solve #8 before merging to master :)

**Comment by p-avital** [comment]
This has been merged a while ago, thanks a lot for your contribution again :)
